### ISSUE TITLE
Split repository into categories

### ISSUE THREAD

**Issue by dylanaraps** [kissx/packages#9]
While the package count in the main repository is small, I want to explore the idea of splitting the repository into categories. This is as simple as adding an additional sub-directory in `repo/` for each category. 

The user would then be able to only add the categories they need to `KISS_PATH`. The code is already in place for something like this. Categories could be split into `shells`, `wm`, `coreutils`, etc. This would make discoverability of alternative packages easy.

An issue arises when the user wants to enable all categories hence this issue. I'd like to discuss this and see what others think.

**Comment by ekomizer** [comment]
Would there be any issue if `export KISS_PATH=ALL` will just `find /kiss/repo -mindepth 2 -maxdepth 2 -name $pkg`?

**Comment by dylanaraps** [comment]
Yes. This environment variable needs to be set by yourself currently. In the future (when the distribution is installable) there may be a default location or value.

**Comment by konimex** [comment]
Good idea, but I'd prefer a CRUX `ports`-like system where this repo would exclusively cover "core" packages of a Linux system.

-----

>An issue arises when the user wants to enable all categories hence this issue. I'd like to discuss this and see what others think.

Maybe we can use something like the `$PATH` system separated with `:`, but it is a problem if we have more than 20 categories.

Or instead of environment variable, a config file containing what category does the user want to enable or disable can be used, and the package manager will iterate through the config file and see if the category is available in the git repo, say `/var/db/repo`, and will fetch the data from there.

Let's say the config file `/etc/kiss/repo` and it will contain

```
compilers
#games (disabled)
ruby
browsers
```

The package manager will iterate through `/var/db/repo/compilers` and so on.
